DROP TABLE IF EXISTS api_key_endpoints CASCADE;

DROP TABLE IF EXISTS endpoints CASCADE;

DROP TABLE IF EXISTS api_keys CASCADE;

DROP TYPE IF EXISTS http_method_enum CASCADE;

DROP FUNCTION IF EXISTS set_updated_at CASCADE;
