services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: test
      ENVIRONMENT: docker
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - kart-challenge-network

  kart-challenge:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: kart-challenge
    image: kart-challenge:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    entrypoint: ["./kart-challenge", "--config", "/mnt/config/config.$ENVIRONMENT.yaml"]
    networks:
      - kart-challenge-network
    volumes:
      - ./promocodes:/mnt/promocodes
      - ./db:/mnt/db
      - ./config:/mnt/config
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
    kart-challenge-network:
        driver: bridge

volumes:
  postgres_data:
    driver: local
