apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kart-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: ENVIRONMENT
              value: "k8s"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "test"
          ports:
            - containerPort: 5432
          resources:
            requests: # Minimum resources guaranteed
              cpu: "500m"      # 0.5 vCPU
              memory: "512Mi"  # 512MB RAM
            limits: # Maximum resources allowed
              cpu: "1"         # 1 vCPU
              memory: "1Gi"    # 1GB RAM
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
