apiVersion: v1
kind: Service
metadata:
  name: kart-challenge
  namespace: kart-challenge
spec:
  type: NodePort
  selector:
    app: kart-challenge
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
