server:
  port: 8080
  host: "127.0.0.1"
  maxCouponCodeCacheSize: 1000
  maxAPIKeyCacheSize: 1000
  maxAPIKeyCacheTTL: 15m
  reqLimitPerIP: 5
  reqBurstPerIP: 10
  reqRateWindow: 1m
  gracefulTimeout: 30s # 30 seconds

database:
  type: "postgres"
  user: "test_user"
  password: "test_password"
  host: "localhost"
  port: 5432
  name: "test"
  sslMode: "disable"
  debug: true
  migrationsFolderPath: db
  maxOpenConnections: 1
  maxIdleConnections: 1
  connMaxIdleTime: 1m
  connMaxLifeTime: 1m

logging:
  level: debug
  jsonFormat: false

telemetry:
  enabled: true
  serviceName: go-template
  host: localhost
  port: 4318

couponCode:
  filePaths:
    - ./promocodes/couponbase1.gz
    - ./promocodes/couponbase2.gz
    - ./promocodes/couponbase3.gz