server:
  port: 8080
  host: "127.0.0.1"

database:
  type: "postgres"
  user: "test_user"
  password: "test_password"
  host: "localhost"
  port: 5432
  name: "test"
  sslMode: "disable"
  debug: true
  migrationsFolderPath: db

logging:
  level: debug
  jsonFormat: false

couponCode:
  unzipped: false
  filePaths:
    - ./promocodes/couponbase1.gz
    - ./promocodes/couponbase2.gz
    - ./promocodes/couponbase3.gz