server:
  port: 8080
  host: "0.0.0.0"

database:
  type: "postgres"
  user: "user"
  password: "password"
  host: "postgres.kart-challenge.svc.cluster.local"
  port: 5432
  name: "test"
  sslMode: "disable"
  debug: true

logging:
  level: debug
  jsonFormat: false

couponCode:
  unzipped: true
  filePaths:
    - /mnt/promocodes/couponbase1.gz
    - /mnt/promocodes/couponbase2.gz
    - /mnt/promocodes/couponbase3.gz