resources:
  - namespace/namespace.yaml
  - postgres/secret.yaml
  - postgres/configmap.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - go-template/deployment.yaml
  - go-template/service.yaml
  - go-template/ingress.yaml

configMapGenerator:
  - name: go-template-config
    namespace: go-template
    files:
      - config.k8s.yaml=go-template/config.k8s.yaml
    options:
      disableNameSuffixHash: true
